grpc:
  server:
    port: 7000
  client:
    grpc-userService:
      address: static://localhost:9405
      negotiation-type: plaintext
      #if it is not secure TLS call

server:
  port: 9303

spring:
  application:
    name: accountService
  datasource:
    url: jdbc:mysql://localhost:3306/seata_account?allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: accountService-producer-group
    topic: accountTopic
    rollback-topic: accountRollbackTopic
  consumer:
    group: accountService-consumer-group
